name: Build mxnet on multiple platforms

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set CMake version
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.31.0"
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"
      - name: Check compiler version
        run: ${CC:-cc} --version
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build
        uses: threeal/cmake-action@v2.1.0

